version: "3.8"

services:
  querymate:
    build: .
    container_name: querymate
    ports:
      - "8501:8501"
    env_file:
      - .env
    network_mode: "host"  # für WSL, damit Ollama erreichbar ist
    restart: unless-stopped